'use client';
import { useEffect, useState } from 'react';

/**
 * Calibration Ledger — one screen, no scroll (brief §6).
 *
 * What was removed and why:
 *  • Three per-persona reliability diagrams generated by a hardcoded
 *    "deterministic placeholder diagonal". 31 resolved claims across
 *    three personas cannot produce three near-perfect diagonals; the
 *    curves were drawn, not measured. Replaced by ONE real diagram
 *    with per-bin counts and uncertainty whiskers.
 *  • Five aggregate tiles that duplicated the global ledger strip
 *    directly above them, three of which read "—".
 *  • A methodology essay occupying the first fifth of the screen.
 *
 * Every number on this page names its TRACK and its n. Below the
 * sample floor a track reports "Calibrating" and no figure — the rule
 * the Reputation Note already applies to creators, applied here to the
 * house as well.
 */

interface Headline {
  brier: number | null; skill: number | null; base_rate: number | null; sharpness: number | null;
}
interface Integrity {
  issued: number; sealed: number; sealed_pct: number | null;
  resolved_total: number; median_lead_days: number | null;
}
interface Bin { bin: number; predicted: number; observed: number | null; n: number }
interface Family {
  feature: string; n: number; brier: number | null; log_loss: number | null;
  base_rate: number | null; skill: number | null; degenerate: boolean; thin: boolean;
}
interface TrackData {
  key: string; label: string; sublabel: string;
  issued: number; resolved: number; void: number; open: number; calibrating: boolean;
  headline: Headline | null; integrity: Integrity; reliability: Bin[];
  history: Array<{ week: string; brier: number; n: number }>;
  cohorts?: Cohort[];
  families: Family[];
}
interface Cohort {
  day: string; issued: number; n: number; open: number; complete: boolean;
  sum_brier: number; sum_y: number; sum_absdev: number;
  brier: number | null; base_rate: number | null; sharpness: number | null; skill: number | null;
}
interface Change { at: string; pr: string; note: string }
interface ObservableFamily {
  key: string; source: string; verdict: 'admit' | 'exclude'; reason: string;
  events: number | null; base_rate: number | null; measured_n?: number | null; issuing?: boolean;
}
interface Payload {
  tracks: TrackData[]; min_sample: number;
  observable_families: ObservableFamily[]; generated_at?: string; error?: string;
  changes?: Change[]; cohorts_error?: string | null;
}

export default function CalibrationWorkspace() {
  const [data, setData] = useState<Payload | null>(null);
  const [selected, setSelected] = useState<string>('house');

  useEffect(() => {
    fetch('/api/intel/calibration/ledger')
      .then(r => r.json())
      .then((j: Payload) => setData(j))
      .catch(() => setData({ tracks: [], min_sample: 10, observable_families: [], error: 'unavailable' }));
  }, []);

  if (!data) {
    return <div style={{ padding: 24 }}><p className="eyebrow">Loading ledger…</p></div>;
  }
  if (data.error || data.tracks.length === 0) {
    return (
      <div style={{ padding: 24 }}>
        <p className="eyebrow text-eykon-ink-faint" >
          Ledger unavailable — no fixture is substituted for a track record.
        </p>
      </div>
    );
  }

  const track = data.tracks.find(t => t.key === selected) ?? data.tracks[0];

  return (
    <div
      className="intel-3col"
      style={{ ['--intel-l' as string]: '250px', ['--intel-r' as string]: '300px', minHeight: 620 } as React.CSSProperties}
    >
      {/* ── LEFT ── */}
      <aside className="bg-eykon-bg-navy p-[14px]">
        <Head>① Track</Head>
        <div className="flex flex-col" style={{ gap: 4, marginTop: 10 }}>
          {data.tracks.map(t => (
            <button
              key={t.key}
              onClick={() => setSelected(t.key)}
              style={{
                textAlign: 'left', padding: '8px 10px', cursor: 'pointer', borderRadius: 2,
                background: selected === t.key ? 'rgba(25,208,184,0.07)' : 'var(--bg-panel)',
                border: `1px solid ${selected === t.key ? 'var(--teal)' : 'var(--rule-soft)'}`,
                color: 'var(--ink)', fontFamily: 'var(--f-mono)', fontSize: 11,
              }}
            >
              <span className="flex items-center" style={{ justifyContent: 'space-between' }}>
                <span>{t.label}</span>
                <span style={{ color: selected === t.key ? 'var(--teal)' : 'var(--ink-faint)' }}>
                  n={t.resolved}
                </span>
              </span>
              <span style={{ display: 'block', marginTop: 2, fontSize: 9, color: 'var(--ink-faint)' }}>
                {t.sublabel}
              </span>
            </button>
          ))}
        </div>
        <p style={{ marginTop: 10, fontFamily: 'var(--f-mono)', fontSize: 9, lineHeight: 1.55, color: 'var(--ink-faint)' }}>
          tracks never blend · house is a reference line, never a rank
        </p>

        <div style={{ marginTop: 16 }}>
          <Head>② Integrity</Head>
          <div className="mt-[8px]">
            <KV
              k="commit-reveal"
              v={`${track.integrity.sealed} / ${track.integrity.issued}`}
              warn={track.integrity.sealed === 0 && track.integrity.issued > 0}
            />
            <KV k="resolved" v={String(track.integrity.resolved_total)} />
            <KV k="void (no look)" v={String(track.void)} />
            <KV k="median lead" v={track.integrity.median_lead_days == null ? '—' : `${track.integrity.median_lead_days} d`} />
          </div>
          {track.integrity.sealed === 0 && track.integrity.issued > 0 && (
            <p style={{ marginTop: 6, fontFamily: 'var(--f-mono)', fontSize: 9, lineHeight: 1.5, color: 'var(--amber)' }}>
              no claim in this track carries a commit hash — these rows were registered before sealing was enforced, and
              cannot be presented as tamper-evident
            </p>
          )}
          <p style={{ marginTop: 6, fontFamily: 'var(--f-mono)', fontSize: 9, lineHeight: 1.5, color: 'var(--ink-faint)' }}>
            voids are excluded from scoring, never counted as wins
          </p>
        </div>

        <div style={{ marginTop: 16 }}>
          <Head>③ Observable families</Head>
          <div className="mt-[8px]">
            {data.observable_families.map(f => (
              <div
                key={f.key}
                className="flex items-center"
                style={{ justifyContent: 'space-between', gap: 6, fontFamily: 'var(--f-mono)', fontSize: 10, padding: '3px 0' }}
              >
                <span style={{ color: f.verdict === 'admit' ? 'var(--ink-dim)' : 'var(--ink-faint)' }} title={f.reason}>
                  {f.key}
                </span>
                {f.verdict === 'exclude' ? (
                  <Tag>excluded</Tag>
                ) : (
                  <span style={{ color: 'var(--ink-faint)', fontSize: 9, whiteSpace: 'nowrap' }}>
                    {f.base_rate == null ? 'base —' : `base ${f.base_rate}${f.measured_n ? ` (n=${f.measured_n})` : ''}${f.issuing ? ' · issuing' : ''}`} · {f.events ?? '—'}
                  </span>
                )}
              </div>
            ))}
          </div>
          <p style={{ marginTop: 6, fontFamily: 'var(--f-mono)', fontSize: 9, lineHeight: 1.5, color: 'var(--ink-faint)' }}>
            base rate must be measured before a family scores — a claim that is 95% true is not a test
          </p>
        </div>
      </aside>

      {/* ── MIDDLE ── */}
      <section style={{ background: 'var(--bg-navy)', padding: 16 }}>
        <div className="grid" style={{ gridTemplateColumns: 'repeat(4, 1fr)', gap: 8 }}>
          {/* The window is part of the number. The global strip reports a
              30-day mean; this page reports all-time. Both are correct and
              they differ — unlabelled, they read as a contradiction. */}
          <Tile label={`Brier · ${track.label.toLowerCase()}`} value={fmt(track.headline?.brier)} sub={`all resolved · n=${track.resolved}`} calibrating={track.calibrating} />
          <Tile label="Skill vs base rate" value={fmtSigned(track.headline?.skill)} sub={track.headline?.base_rate == null ? 'no base rate yet' : `base rate ${track.headline.base_rate}`} calibrating={track.calibrating} accent />
          <Tile label="Resolution" value={`${track.resolved} / ${track.resolved + track.void}`} sub={`${track.void} void · ${track.open} open`} />
          <Tile label="Sharpness" value={fmt(track.headline?.sharpness)} sub="avg distance from 0.5" calibrating={track.calibrating} />
        </div>

        <div style={{ marginTop: 12, border: '1px solid var(--rule-soft)', background: 'var(--bg-panel)', padding: 12 }}>
          <div className="flex items-center" style={{ justifyContent: 'space-between' }}>
            <Head>④ Reliability · {track.label.toLowerCase()}</Head>
            <span style={{ fontFamily: 'var(--f-mono)', fontSize: 9, color: 'var(--ink-faint)' }}>
              bar = claims in bin · whisker = uncertainty at that n
            </span>
          </div>
          <Reliability bins={track.reliability} />
        </div>

        <div style={{ marginTop: 12, border: '1px solid var(--rule-soft)', background: 'var(--bg-panel)', padding: 12 }}>
          <Head>⑤ Brier by resolution week</Head>
          <History points={track.history} />
        </div>

        <div style={{ marginTop: 12, border: '1px solid var(--rule-soft)', background: 'var(--bg-panel)', padding: 12 }}>
          <Head>⑤b Skill by issuance cohort</Head>
          <Cohorts points={track.cohorts ?? []} changes={data.changes ?? []} error={data.cohorts_error ?? null} weekly={track.key === 'house'} />
        </div>
      </section>

      {/* ── RIGHT ── */}
      <aside className="bg-eykon-bg-navy p-[14px]">
        <Head>⑥ By claim family</Head>
        <div className="flex flex-col" style={{ gap: 4, marginTop: 10 }}>
          {track.families.length === 0 && (
            <p style={{ fontFamily: 'var(--f-mono)', fontSize: 10, color: 'var(--ink-faint)' }}>
              no resolved claims in this track
            </p>
          )}
          {track.families.map(f => (
            <div
              key={f.feature}
              style={{ border: '1px solid var(--rule-soft)', background: 'var(--bg-panel)', padding: '6px 8px', fontFamily: 'var(--f-mono)', fontSize: 10.5 }}
            >
              <div className="flex items-center" style={{ justifyContent: 'space-between', gap: 6 }}>
                <span className="text-eykon-ink-dim">{f.feature}</span>
                <span className="num-lg" style={{ fontSize: 11, color: f.thin ? 'var(--ink-faint)' : 'var(--teal)' }}>
                  {f.brier == null ? '—' : f.brier.toFixed(3)}
                </span>
              </div>
              {/* Skill, not just Brier: a family whose event almost never
                  happens scores a flattering Brier by predicting "no"
                  forever, so Brier alone is not comparable across
                  families. Skill is measured against each family's OWN
                  base rate. */}
              <div className="flex items-center" style={{ justifyContent: 'space-between', gap: 6, marginTop: 2 }}>
                <span style={{ fontSize: 9, color: 'var(--ink-faint)' }}>
                  n={f.n}{f.base_rate != null ? ` · base ${f.base_rate}` : ''}
                </span>
                {f.degenerate ? (
                  <Tag>base 0/1 · skill undefined</Tag>
                ) : f.skill != null ? (
                  <span style={{ fontSize: 9.5, color: f.skill >= 0 ? 'var(--teal)' : 'var(--amber)' }}>
                    skill {f.skill >= 0 ? '+' : ''}{f.skill.toFixed(2)}
                  </span>
                ) : null}
              </div>
              {f.thin && (
                <div style={{ marginTop: 2 }}><Tag>thin · n&lt;{data.min_sample}</Tag></div>
              )}
            </div>
          ))}
        </div>

        <div style={{ marginTop: 16 }}>
          <Head>⑦ Standing</Head>
          <p style={{ marginTop: 8, fontFamily: 'var(--f-mono)', fontSize: 10, lineHeight: 1.6, color: 'var(--ink-faint)' }}>
            Creator standing — absolute band (gates paid Spaces) and percentile among creators — is computed by the
            Reputation Note and shown on creator profiles. The house is deliberately excluded from that ranked
            population: a percentile is zero-sum, so a benchmark inside it would lower every creator by arithmetic.
          </p>
        </div>
      </aside>
    </div>
  );
}

/**
 * Real reliability diagram. Points are observed frequency against
 * predicted probability; the dashed line is perfect calibration.
 * Bar height encodes how many claims sit in each bin and the whisker
 * is a normal-approximation interval at that n — so a bin holding two
 * claims visibly cannot carry an argument.
 */
function Reliability({ bins }: { bins: Bin[] }) {
  const W = 660, H = 200, PAD_L = 34, PAD_B = 26, PAD_T = 8;
  const plotW = W - PAD_L - 12, plotH = H - PAD_B - PAD_T;
  const maxN = Math.max(1, ...bins.map(b => b.n));
  const x = (p: number) => PAD_L + p * plotW;
  const y = (v: number) => PAD_T + (1 - v) * plotH;
  const populated = bins.filter(b => b.n > 0 && b.observed != null);

  if (populated.length === 0) {
    return (
      <p style={{ fontFamily: 'var(--f-mono)', fontSize: 10.5, color: 'var(--ink-faint)', padding: '20px 0' }}>
        No resolved claims in this track yet — no diagram is drawn.
      </p>
    );
  }

  return (
    <svg width="100%" height={H} viewBox={`0 0 ${W} ${H}`} aria-hidden style={{ marginTop: 6 }}>
      <line x1={x(0)} y1={y(0)} x2={x(1)} y2={y(1)} stroke="var(--rule-strong)" strokeWidth={1} strokeDasharray="4 3" />
      <line x1={x(0)} y1={y(0)} x2={x(1)} y2={y(0)} stroke="var(--rule-soft)" strokeWidth={1} />
      <line x1={x(0)} y1={y(0)} x2={x(0)} y2={y(1)} stroke="var(--rule-soft)" strokeWidth={1} />
      {bins.map(b => (
        b.n > 0 ? (
          <rect
            key={`bar${b.bin}`}
            x={x(b.predicted) - 9}
            y={y(0) - (b.n / maxN) * 46}
            width={18}
            height={(b.n / maxN) * 46}
            fill="var(--rule-soft)"
            opacity={0.9}
          />
        ) : null
      ))}
      {populated.map(b => {
        const obs = b.observed as number;
        // Normal approximation of the standard error of a proportion.
        const se = Math.sqrt(Math.max(obs * (1 - obs), 0.02) / b.n);
        const lo = Math.max(0, obs - 1.64 * se), hi = Math.min(1, obs + 1.64 * se);
        return (
          <g key={`pt${b.bin}`}>
            <line x1={x(b.predicted)} y1={y(lo)} x2={x(b.predicted)} y2={y(hi)} stroke="var(--teal)" strokeWidth={1.5} opacity={0.5} />
            <circle cx={x(b.predicted)} cy={y(obs)} r={4} fill="var(--teal)" />
          </g>
        );
      })}
      <text x={x(0)} y={H - 8} fontSize={9} fill="var(--ink-faint)" fontFamily="var(--f-mono)">0.0</text>
      <text x={x(0.5) - 44} y={H - 8} fontSize={9} fill="var(--ink-faint)" fontFamily="var(--f-mono)">predicted probability</text>
      <text x={x(1) - 14} y={H - 8} fontSize={9} fill="var(--ink-faint)" fontFamily="var(--f-mono)">1.0</text>
      <text x={4} y={y(1) + 8} fontSize={9} fill="var(--ink-faint)" fontFamily="var(--f-mono)">1.0</text>
      <text x={4} y={y(0)} fontSize={9} fill="var(--ink-faint)" fontFamily="var(--f-mono)">0.0</text>
    </svg>
  );
}

function History({ points }: { points: Array<{ week: string; brier: number; n: number }> }) {
  if (points.length < 2) {
    return (
      <p style={{ fontFamily: 'var(--f-mono)', fontSize: 10, color: 'var(--ink-faint)', padding: '10px 0' }}>
        {points.length === 0 ? 'No resolved claims yet.' : 'One week of resolutions — a trend needs at least two.'}
      </p>
    );
  }
  const W = 660, H = 70;
  const max = Math.max(...points.map(p => p.brier), 0.5);
  const step = W / Math.max(points.length - 1, 1);
  const path = points.map((p, i) => `${i * step},${H - 8 - (p.brier / max) * (H - 20)}`).join(' ');
  return (
    <>
      <svg width="100%" height={H} viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none" aria-hidden style={{ marginTop: 6 }}>
        <polyline points={path} fill="none" stroke="var(--teal)" strokeWidth={2} />
      </svg>
      <p style={{ fontFamily: 'var(--f-mono)', fontSize: 9, color: 'var(--ink-faint)', margin: 0 }}>
        {points[0].week} → {points[points.length - 1].week} · lower is better
      </p>
    </>
  );
}

function Tile({ label, value, sub, calibrating, accent }: {
  label: string; value: string; sub: string; calibrating?: boolean; accent?: boolean;
}) {
  return (
    <div style={{ background: 'var(--bg-panel)', border: '1px solid var(--rule-soft)', padding: '9px 11px' }}>
      <div className="eyebrow" style={{ marginBottom: 5 }}>{label}</div>
      <div className="num-lg" style={{ fontSize: calibrating ? 13 : 20, color: calibrating ? 'var(--ink-faint)' : accent ? 'var(--teal)' : 'var(--ink)' }}>
        {calibrating ? 'Calibrating' : value}
      </div>
      <div style={{ fontFamily: 'var(--f-mono)', fontSize: 9, color: 'var(--ink-faint)', marginTop: 3 }}>{sub}</div>
    </div>
  );
}

function KV({ k, v, warn }: { k: string; v: string; warn?: boolean }) {
  return (
    <div className="flex items-center" style={{ justifyContent: 'space-between', fontFamily: 'var(--f-mono)', fontSize: 10.5, padding: '2px 0' }}>
      <span className="text-eykon-ink-faint">{k}</span>
      <span style={{ color: warn ? 'var(--amber)' : 'var(--ink-dim)' }}>{v}</span>
    </div>
  );
}

function Tag({ children }: { children: React.ReactNode }) {
  return (
    <span style={{ fontSize: 8.5, letterSpacing: '0.06em', color: 'var(--ink-faint)', border: '1px solid var(--rule-soft)', padding: '0 4px', whiteSpace: 'nowrap' }}>
      {children}
    </span>
  );
}

/**
 * Skill by ISSUANCE cohort — the only view in which a change of forecaster is
 * visible. The headline is cumulative and carries every early cohort forever;
 * "Brier by resolution week" mixes claims issued under different forecasters.
 *
 * Two honesty rules, both from this ledger's own history:
 *   · a cohort is COMPARABLE only once every claim in it has passed its
 *     deadline. The claims that resolve first are the ones that reappeared
 *     first (#401 censoring): on 2026-09-08 the first 43 of 6,607 claims from
 *     one cohort read +0.296 while the rest had not had time to fail.
 *     Incomplete cohorts are drawn hollow and labelled, never as a bar to
 *     compare against.
 *   · a cohort with sharpness 0.000 is the flat 0.5 prior — the forecaster
 *     said nothing. Drawn grey and labelled, so the trajectory reads as
 *     "no forecaster → forecaster", not as a lucky week.
 *
 * Sums are re-bucketed here (days → ISO weeks for the house track, which
 * issues weekly), so the derived numbers are exact, not averages of averages.
 */
function Cohorts({ points, changes, error, weekly }: {
  points: Cohort[]; changes: Change[]; error: string | null; weekly: boolean;
}) {
  if (error) {
    return (
      <p style={{ fontFamily: 'var(--f-mono)', fontSize: 10, color: 'var(--amber)', padding: '10px 0' }}>
        cohort view unavailable — {error}
      </p>
    );
  }
  const bucketed = weekly ? bucketWeeks(points) : points;
  const shown = bucketed.filter(c => c.issued > 0);
  if (shown.length < 2) {
    return (
      <p style={{ fontFamily: 'var(--f-mono)', fontSize: 10, color: 'var(--ink-faint)', padding: '10px 0' }}>
        {shown.length === 0 ? 'No cohorts in the last 120 days.' : 'One cohort — a trajectory needs at least two.'}
      </p>
    );
  }
  const W = 660, H = 92, PAD = 10;
  const step = W / shown.length;
  const skills = shown.map(c => c.skill ?? 0);
  const lo = Math.min(-0.5, ...skills), hi = Math.max(0.25, ...skills);
  const y = (v: number) => PAD + ((hi - v) / (hi - lo)) * (H - PAD * 2);
  const zero = y(0);
  const firstDay = Date.parse(`${shown[0].day}T00:00:00Z`);
  const lastDay = Date.parse(`${shown[shown.length - 1].day}T00:00:00Z`) + 86_400_000 * (weekly ? 7 : 1);
  const xOf = (iso: string) => ((Date.parse(iso) - firstDay) / (lastDay - firstDay)) * W;
  return (
    <>
      <svg width="100%" height={H + 14} viewBox={`0 0 ${W} ${H + 14}`} preserveAspectRatio="none" aria-label="skill by issuance cohort" style={{ marginTop: 6 }}>
        <line x1={0} x2={W} y1={zero} y2={zero} stroke="var(--rule-strong)" strokeWidth={1} strokeDasharray="3 3" />
        {shown.map((c, i) => {
          const flat = (c.sharpness ?? 1) < 0.005;
          const s = c.skill ?? 0;
          const top = Math.min(y(s), zero), h = Math.max(1, Math.abs(y(s) - zero));
          const x = i * step + step * 0.15, bw = step * 0.7;
          const fill = !c.complete ? 'none' : flat ? 'var(--ink-ghost)' : s < 0 ? 'var(--coral)' : 'var(--green)';
          const title = `${c.day}${weekly ? ' week' : ''} · issued ${c.issued} · resolved ${c.n}${c.complete ? '' : ` · open ${c.open} — not comparable`} · skill ${c.skill == null ? '—' : c.skill.toFixed(3)} · sharpness ${c.sharpness == null ? '—' : c.sharpness.toFixed(3)}${flat ? ' (flat prior)' : ''}`;
          return (
            <g key={c.day}>
              <rect x={x} y={top} width={bw} height={h} fill={fill} stroke={!c.complete ? 'var(--ink-faint)' : 'none'} strokeDasharray={!c.complete ? '2 2' : undefined} opacity={c.complete ? 0.9 : 0.7}>
                <title>{title}</title>
              </rect>
              <text x={x + bw / 2} y={H + 10} fontSize={7} fill="var(--ink-faint)" textAnchor="middle" fontFamily="var(--f-mono)">{c.day.slice(5)}</text>
            </g>
          );
        })}
        {changes.map(ch => {
          const cx = xOf(ch.at);
          if (cx < 0 || cx > W) return null;
          return (
            <g key={ch.at}>
              <line x1={cx} x2={cx} y1={2} y2={H - 2} stroke="var(--amber)" strokeWidth={1} strokeDasharray="2 2" />
              <text x={cx + 2} y={9} fontSize={7} fill="var(--amber)" fontFamily="var(--f-mono)">{ch.pr}<title>{`${ch.at} · ${ch.note}`}</title></text>
            </g>
          );
        })}
      </svg>
      <p style={{ fontFamily: 'var(--f-mono)', fontSize: 9, color: 'var(--ink-faint)', margin: 0, lineHeight: 1.6 }}>
        skill = 1 − Brier ÷ base·(1−base), by {weekly ? 'issuance week' : 'issuance day'} · complete cohorts solid · open cohorts hollow (not comparable) · grey = flat 0.5 prior (sharpness 0) · amber marks = forecaster changes
      </p>
    </>
  );
}

function bucketWeeks(points: Cohort[]): Cohort[] {
  const by = new Map<string, Cohort>();
  for (const c of points) {
    const d = new Date(`${c.day}T00:00:00Z`);
    const dow = (d.getUTCDay() + 6) % 7;                 // Monday = 0
    const monday = new Date(d.getTime() - dow * 86_400_000).toISOString().slice(0, 10);
    const acc = by.get(monday) ?? { day: monday, issued: 0, n: 0, open: 0, complete: true, sum_brier: 0, sum_y: 0, sum_absdev: 0, brier: null, base_rate: null, sharpness: null, skill: null };
    acc.issued += c.issued; acc.n += c.n; acc.open += c.open; acc.complete = acc.complete && c.complete;
    acc.sum_brier += Number(c.sum_brier); acc.sum_y += Number(c.sum_y); acc.sum_absdev += Number(c.sum_absdev);
    by.set(monday, acc);
  }
  return [...by.values()].sort((a, b) => a.day.localeCompare(b.day)).map(a => {
    if (a.n === 0) return a;
    const brier = a.sum_brier / a.n, base = a.sum_y / a.n, sharp = a.sum_absdev / a.n;
    const denom = base * (1 - base);
    return { ...a, brier, base_rate: base, sharpness: sharp, skill: denom > 0.001 ? 1 - brier / denom : null };
  });
}

function Head({ children }: { children: React.ReactNode }) {
  return (
    <h3 className="panel-title flex items-center gap-[8px]" >
      <span style={{ width: 3, height: 12, background: 'var(--teal)' }} />
      {children}
    </h3>
  );
}

function fmt(v: number | null | undefined): string {
  return v == null ? '—' : v.toFixed(3);
}
function fmtSigned(v: number | null | undefined): string {
  return v == null ? '—' : `${v >= 0 ? '+' : ''}${v.toFixed(2)}`;
}
