'use client';
import { useEffect, useState } from 'react';

/**
 * Calibration Ledger — one screen, no scroll (brief §6).
 *
 * What was removed and why:
 *  • Three per-persona reliability diagrams generated by a hardcoded
 *    "deterministic placeholder diagonal". 31 resolved claims across
 *    three personas cannot produce three near-perfect diagonals; the
 *    curves were drawn, not measured. Replaced by ONE real diagram
 *    with per-bin counts and uncertainty whiskers.
 *  • Five aggregate tiles that duplicated the global ledger strip
 *    directly above them, three of which read "—".
 *  • A methodology essay occupying the first fifth of the screen.
 *
 * Every number on this page names its TRACK and its n. Below the
 * sample floor a track reports "Calibrating" and no figure — the rule
 * the Reputation Note already applies to creators, applied here to the
 * house as well.
 */

interface Headline {
  brier: number | null; skill: number | null; base_rate: number | null; sharpness: number | null;
}
interface Integrity {
  issued: number; sealed: number; sealed_pct: number | null;
  resolved_total: number; median_lead_days: number | null;
}
interface Bin { bin: number; predicted: number; observed: number | null; n: number }
interface Family { feature: string; n: number; brier: number | null; log_loss: number | null; thin: boolean }
interface TrackData {
  key: string; label: string; sublabel: string;
  issued: number; resolved: number; void: number; open: number; calibrating: boolean;
  headline: Headline | null; integrity: Integrity; reliability: Bin[];
  history: Array<{ week: string; brier: number; n: number }>;
  families: Family[];
}
interface ObservableFamily {
  key: string; source: string; verdict: 'admit' | 'exclude'; reason: string;
  events: number | null; base_rate: number | null;
}
interface Payload {
  tracks: TrackData[]; min_sample: number;
  observable_families: ObservableFamily[]; generated_at?: string; error?: string;
}

export default function CalibrationWorkspace() {
  const [data, setData] = useState<Payload | null>(null);
  const [selected, setSelected] = useState<string>('house');

  useEffect(() => {
    fetch('/api/intel/calibration/ledger')
      .then(r => r.json())
      .then((j: Payload) => setData(j))
      .catch(() => setData({ tracks: [], min_sample: 10, observable_families: [], error: 'unavailable' }));
  }, []);

  if (!data) {
    return <div style={{ padding: 24 }}><p className="eyebrow">Loading ledger…</p></div>;
  }
  if (data.error || data.tracks.length === 0) {
    return (
      <div style={{ padding: 24 }}>
        <p className="eyebrow" style={{ color: 'var(--ink-faint)' }}>
          Ledger unavailable — no fixture is substituted for a track record.
        </p>
      </div>
    );
  }

  const track = data.tracks.find(t => t.key === selected) ?? data.tracks[0];

  return (
    <div
      className="grid"
      style={{ gridTemplateColumns: '250px 1fr 300px', gap: 1, background: 'var(--rule-soft)', minHeight: 620 }}
    >
      {/* ── LEFT ── */}
      <aside style={{ background: 'var(--bg-navy)', padding: 14 }}>
        <Head>① Track</Head>
        <div className="flex flex-col" style={{ gap: 4, marginTop: 10 }}>
          {data.tracks.map(t => (
            <button
              key={t.key}
              onClick={() => setSelected(t.key)}
              style={{
                textAlign: 'left', padding: '8px 10px', cursor: 'pointer', borderRadius: 2,
                background: selected === t.key ? 'rgba(25,208,184,0.07)' : 'var(--bg-panel)',
                border: `1px solid ${selected === t.key ? 'var(--teal)' : 'var(--rule-soft)'}`,
                color: 'var(--ink)', fontFamily: 'var(--f-mono)', fontSize: 11,
              }}
            >
              <span className="flex items-center" style={{ justifyContent: 'space-between' }}>
                <span>{t.label}</span>
                <span style={{ color: selected === t.key ? 'var(--teal)' : 'var(--ink-faint)' }}>
                  n={t.resolved}
                </span>
              </span>
              <span style={{ display: 'block', marginTop: 2, fontSize: 9, color: 'var(--ink-faint)' }}>
                {t.sublabel}
              </span>
            </button>
          ))}
        </div>
        <p style={{ marginTop: 10, fontFamily: 'var(--f-mono)', fontSize: 9, lineHeight: 1.55, color: 'var(--ink-faint)' }}>
          tracks never blend · house is a reference line, never a rank
        </p>

        <div style={{ marginTop: 16 }}>
          <Head>② Integrity</Head>
          <div style={{ marginTop: 8 }}>
            <KV
              k="commit-reveal"
              v={`${track.integrity.sealed} / ${track.integrity.issued}`}
              warn={track.integrity.sealed === 0 && track.integrity.issued > 0}
            />
            <KV k="resolved" v={String(track.integrity.resolved_total)} />
            <KV k="void (no look)" v={String(track.void)} />
            <KV k="median lead" v={track.integrity.median_lead_days == null ? '—' : `${track.integrity.median_lead_days} d`} />
          </div>
          {track.integrity.sealed === 0 && track.integrity.issued > 0 && (
            <p style={{ marginTop: 6, fontFamily: 'var(--f-mono)', fontSize: 9, lineHeight: 1.5, color: 'var(--amber)' }}>
              no claim in this track carries a commit hash — these rows were registered before sealing was enforced, and
              cannot be presented as tamper-evident
            </p>
          )}
          <p style={{ marginTop: 6, fontFamily: 'var(--f-mono)', fontSize: 9, lineHeight: 1.5, color: 'var(--ink-faint)' }}>
            voids are excluded from scoring, never counted as wins
          </p>
        </div>

        <div style={{ marginTop: 16 }}>
          <Head>③ Observable families</Head>
          <div style={{ marginTop: 8 }}>
            {data.observable_families.map(f => (
              <div
                key={f.key}
                className="flex items-center"
                style={{ justifyContent: 'space-between', gap: 6, fontFamily: 'var(--f-mono)', fontSize: 10, padding: '3px 0' }}
              >
                <span style={{ color: f.verdict === 'admit' ? 'var(--ink-dim)' : 'var(--ink-faint)' }} title={f.reason}>
                  {f.key}
                </span>
                {f.verdict === 'exclude' ? (
                  <Tag>excluded</Tag>
                ) : (
                  <span style={{ color: 'var(--ink-faint)', fontSize: 9, whiteSpace: 'nowrap' }}>
                    {f.base_rate == null ? 'base —' : `base ${f.base_rate}`} · {f.events ?? '—'}
                  </span>
                )}
              </div>
            ))}
          </div>
          <p style={{ marginTop: 6, fontFamily: 'var(--f-mono)', fontSize: 9, lineHeight: 1.5, color: 'var(--ink-faint)' }}>
            base rate must be measured before a family scores — a claim that is 95% true is not a test
          </p>
        </div>
      </aside>

      {/* ── MIDDLE ── */}
      <section style={{ background: 'var(--bg-navy)', padding: 16 }}>
        <div className="grid" style={{ gridTemplateColumns: 'repeat(4, 1fr)', gap: 8 }}>
          <Tile label={`Brier · ${track.label.toLowerCase()}`} value={fmt(track.headline?.brier)} sub={`n=${track.resolved} · lower is better`} calibrating={track.calibrating} />
          <Tile label="Skill vs base rate" value={fmtSigned(track.headline?.skill)} sub={track.headline?.base_rate == null ? 'no base rate yet' : `base rate ${track.headline.base_rate}`} calibrating={track.calibrating} accent />
          <Tile label="Resolution" value={`${track.resolved} / ${track.resolved + track.void}`} sub={`${track.void} void · ${track.open} open`} />
          <Tile label="Sharpness" value={fmt(track.headline?.sharpness)} sub="avg distance from 0.5" calibrating={track.calibrating} />
        </div>

        <div style={{ marginTop: 12, border: '1px solid var(--rule-soft)', background: 'var(--bg-panel)', padding: 12 }}>
          <div className="flex items-center" style={{ justifyContent: 'space-between' }}>
            <Head>④ Reliability · {track.label.toLowerCase()}</Head>
            <span style={{ fontFamily: 'var(--f-mono)', fontSize: 9, color: 'var(--ink-faint)' }}>
              bar = claims in bin · whisker = uncertainty at that n
            </span>
          </div>
          <Reliability bins={track.reliability} />
        </div>

        <div style={{ marginTop: 12, border: '1px solid var(--rule-soft)', background: 'var(--bg-panel)', padding: 12 }}>
          <Head>⑤ Brier by resolution week</Head>
          <History points={track.history} />
        </div>
      </section>

      {/* ── RIGHT ── */}
      <aside style={{ background: 'var(--bg-navy)', padding: 14 }}>
        <Head>⑥ By claim family</Head>
        <div className="flex flex-col" style={{ gap: 4, marginTop: 10 }}>
          {track.families.length === 0 && (
            <p style={{ fontFamily: 'var(--f-mono)', fontSize: 10, color: 'var(--ink-faint)' }}>
              no resolved claims in this track
            </p>
          )}
          {track.families.map(f => (
            <div
              key={f.feature}
              style={{ border: '1px solid var(--rule-soft)', background: 'var(--bg-panel)', padding: '6px 8px', fontFamily: 'var(--f-mono)', fontSize: 10.5 }}
            >
              <div className="flex items-center" style={{ justifyContent: 'space-between', gap: 6 }}>
                <span style={{ color: 'var(--ink-dim)' }}>{f.feature}</span>
                <span className="num-lg" style={{ fontSize: 11, color: f.thin ? 'var(--ink-faint)' : 'var(--teal)' }}>
                  {f.brier == null ? '—' : f.brier.toFixed(3)}
                </span>
              </div>
              <div className="flex items-center" style={{ justifyContent: 'space-between', gap: 6, marginTop: 2 }}>
                <span style={{ fontSize: 9, color: 'var(--ink-faint)' }}>
                  n={f.n}{f.log_loss != null ? ` · log-loss ${f.log_loss.toFixed(3)}` : ''}
                </span>
                {f.thin && <Tag>thin · n&lt;{data.min_sample}</Tag>}
              </div>
            </div>
          ))}
        </div>

        <div style={{ marginTop: 16 }}>
          <Head>⑦ Standing</Head>
          <p style={{ marginTop: 8, fontFamily: 'var(--f-mono)', fontSize: 10, lineHeight: 1.6, color: 'var(--ink-faint)' }}>
            Creator standing — absolute band (gates paid Spaces) and percentile among creators — is computed by the
            Reputation Note and shown on creator profiles. The house is deliberately excluded from that ranked
            population: a percentile is zero-sum, so a benchmark inside it would lower every creator by arithmetic.
          </p>
        </div>
      </aside>
    </div>
  );
}

/**
 * Real reliability diagram. Points are observed frequency against
 * predicted probability; the dashed line is perfect calibration.
 * Bar height encodes how many claims sit in each bin and the whisker
 * is a normal-approximation interval at that n — so a bin holding two
 * claims visibly cannot carry an argument.
 */
function Reliability({ bins }: { bins: Bin[] }) {
  const W = 660, H = 200, PAD_L = 34, PAD_B = 26, PAD_T = 8;
  const plotW = W - PAD_L - 12, plotH = H - PAD_B - PAD_T;
  const maxN = Math.max(1, ...bins.map(b => b.n));
  const x = (p: number) => PAD_L + p * plotW;
  const y = (v: number) => PAD_T + (1 - v) * plotH;
  const populated = bins.filter(b => b.n > 0 && b.observed != null);

  if (populated.length === 0) {
    return (
      <p style={{ fontFamily: 'var(--f-mono)', fontSize: 10.5, color: 'var(--ink-faint)', padding: '20px 0' }}>
        No resolved claims in this track yet — no diagram is drawn.
      </p>
    );
  }

  return (
    <svg width="100%" height={H} viewBox={`0 0 ${W} ${H}`} aria-hidden style={{ marginTop: 6 }}>
      <line x1={x(0)} y1={y(0)} x2={x(1)} y2={y(1)} stroke="var(--rule-strong)" strokeWidth={1} strokeDasharray="4 3" />
      <line x1={x(0)} y1={y(0)} x2={x(1)} y2={y(0)} stroke="var(--rule-soft)" strokeWidth={1} />
      <line x1={x(0)} y1={y(0)} x2={x(0)} y2={y(1)} stroke="var(--rule-soft)" strokeWidth={1} />
      {bins.map(b => (
        b.n > 0 ? (
          <rect
            key={`bar${b.bin}`}
            x={x(b.predicted) - 9}
            y={y(0) - (b.n / maxN) * 46}
            width={18}
            height={(b.n / maxN) * 46}
            fill="var(--rule-soft)"
            opacity={0.9}
          />
        ) : null
      ))}
      {populated.map(b => {
        const obs = b.observed as number;
        // Normal approximation of the standard error of a proportion.
        const se = Math.sqrt(Math.max(obs * (1 - obs), 0.02) / b.n);
        const lo = Math.max(0, obs - 1.64 * se), hi = Math.min(1, obs + 1.64 * se);
        return (
          <g key={`pt${b.bin}`}>
            <line x1={x(b.predicted)} y1={y(lo)} x2={x(b.predicted)} y2={y(hi)} stroke="var(--teal)" strokeWidth={1.5} opacity={0.5} />
            <circle cx={x(b.predicted)} cy={y(obs)} r={4} fill="var(--teal)" />
          </g>
        );
      })}
      <text x={x(0)} y={H - 8} fontSize={9} fill="var(--ink-faint)" fontFamily="var(--f-mono)">0.0</text>
      <text x={x(0.5) - 44} y={H - 8} fontSize={9} fill="var(--ink-faint)" fontFamily="var(--f-mono)">predicted probability</text>
      <text x={x(1) - 14} y={H - 8} fontSize={9} fill="var(--ink-faint)" fontFamily="var(--f-mono)">1.0</text>
      <text x={4} y={y(1) + 8} fontSize={9} fill="var(--ink-faint)" fontFamily="var(--f-mono)">1.0</text>
      <text x={4} y={y(0)} fontSize={9} fill="var(--ink-faint)" fontFamily="var(--f-mono)">0.0</text>
    </svg>
  );
}

function History({ points }: { points: Array<{ week: string; brier: number; n: number }> }) {
  if (points.length < 2) {
    return (
      <p style={{ fontFamily: 'var(--f-mono)', fontSize: 10, color: 'var(--ink-faint)', padding: '10px 0' }}>
        {points.length === 0 ? 'No resolved claims yet.' : 'One week of resolutions — a trend needs at least two.'}
      </p>
    );
  }
  const W = 660, H = 70;
  const max = Math.max(...points.map(p => p.brier), 0.5);
  const step = W / Math.max(points.length - 1, 1);
  const path = points.map((p, i) => `${i * step},${H - 8 - (p.brier / max) * (H - 20)}`).join(' ');
  return (
    <>
      <svg width="100%" height={H} viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none" aria-hidden style={{ marginTop: 6 }}>
        <polyline points={path} fill="none" stroke="var(--teal)" strokeWidth={2} />
      </svg>
      <p style={{ fontFamily: 'var(--f-mono)', fontSize: 9, color: 'var(--ink-faint)', margin: 0 }}>
        {points[0].week} → {points[points.length - 1].week} · lower is better
      </p>
    </>
  );
}

function Tile({ label, value, sub, calibrating, accent }: {
  label: string; value: string; sub: string; calibrating?: boolean; accent?: boolean;
}) {
  return (
    <div style={{ background: 'var(--bg-panel)', border: '1px solid var(--rule-soft)', padding: '9px 11px' }}>
      <div className="eyebrow" style={{ marginBottom: 5 }}>{label}</div>
      <div className="num-lg" style={{ fontSize: calibrating ? 13 : 20, color: calibrating ? 'var(--ink-faint)' : accent ? 'var(--teal)' : 'var(--ink)' }}>
        {calibrating ? 'Calibrating' : value}
      </div>
      <div style={{ fontFamily: 'var(--f-mono)', fontSize: 9, color: 'var(--ink-faint)', marginTop: 3 }}>{sub}</div>
    </div>
  );
}

function KV({ k, v, warn }: { k: string; v: string; warn?: boolean }) {
  return (
    <div className="flex items-center" style={{ justifyContent: 'space-between', fontFamily: 'var(--f-mono)', fontSize: 10.5, padding: '2px 0' }}>
      <span style={{ color: 'var(--ink-faint)' }}>{k}</span>
      <span style={{ color: warn ? 'var(--amber)' : 'var(--ink-dim)' }}>{v}</span>
    </div>
  );
}

function Tag({ children }: { children: React.ReactNode }) {
  return (
    <span style={{ fontSize: 8.5, letterSpacing: '0.06em', color: 'var(--ink-faint)', border: '1px solid var(--rule-soft)', padding: '0 4px', whiteSpace: 'nowrap' }}>
      {children}
    </span>
  );
}

function Head({ children }: { children: React.ReactNode }) {
  return (
    <h3 className="panel-title" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
      <span style={{ width: 3, height: 12, background: 'var(--teal)' }} />
      {children}
    </h3>
  );
}

function fmt(v: number | null | undefined): string {
  return v == null ? '—' : v.toFixed(3);
}
function fmtSigned(v: number | null | undefined): string {
  return v == null ? '—' : `${v >= 0 ? '+' : ''}${v.toFixed(2)}`;
}
