// ─── eYKON brand tokens (§4.8) ─────────────────────────────────
// Single source of truth for palette, fonts, and product strings.
// Mirrors apps/web/app/globals.css and is imported by every export
// surface (PDF in PR 5; Markdown + JSON exports in PR 6; future
// Word/Slides). Keeping CSS variables and TS constants in sync is
// a manual concern — when one changes, update the other.

export const BRAND_TOKENS = {
  // UI dark palette — verbatim from globals.css :root.
  palette: {
    bgVoid:      '#05080F',
    bgNavy:      '#0A1220',
    bgPanel:     '#0F182A',
    bgRaised:    '#15203A',
    bgHover:     '#1A2846',
    rule:        '#1E2C49',
    ruleSoft:    '#15203A',
    ruleStrong:  '#2B3A5C',
    ink:         '#E8EDF5',
    inkDim:      '#98A3B5',
    inkFaint:    '#5A6478',
    inkGhost:    '#3A4256',
    teal:        '#19D0B8',
    tealDim:     '#0E9A88',
    tealDeep:    '#0A5E54',
    amber:       '#D4A24C',
    red:         '#E05D50',
    green:       '#4ABF8A',
    violet:      '#8B7FD8',
    coral:       '#DE7F70',
    wheat:       '#D4A24C',
  },
  // Print palette — high-contrast on white. Used for PDF / exports
  // where the dark-UI scheme would render badly on paper.
  print: {
    bg:        '#FFFFFF',
    ink:       '#0A1220',
    inkDim:    '#5A6478',
    inkFaint:  '#98A3B5',
    accent:    '#0E9A88', // teal-dim — readable on white
    accentBg:  '#E5F7F4',
    rule:      '#D6DBE5',
    ruleStrong:'#A4ADBE',
  },
  // Font family names — used for HTML/CSS contexts. PDFKit and other
  // font-embedded surfaces must bundle the TTFs to honour these;
  // until then they fall back to the renderer's defaults (Helvetica
  // for PDFKit).
  fonts: {
    display: 'Jura',
    body:    'IBM Plex Sans',
    mono:    'IBM Plex Mono',
  },
  product: {
    wordmark:    'eYKON.ai',
    name:        'eYKON Intelligence Analyst',
    tagline:     'Geopolitical intelligence platform',
    confidential: 'Generated by eYKON.ai',
  },
} as const;

export type BrandTokens = typeof BRAND_TOKENS;
