import Anthropic from '@anthropic-ai/sdk';

let anthropicClient: Anthropic | null = null;

export function getAnthropic(): Anthropic {
  if (anthropicClient) return anthropicClient;
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error('Missing ANTHROPIC_API_KEY');
  anthropicClient = new Anthropic({ apiKey });
  return anthropicClient;
}

// ─── Claude Tool Definitions for Conversational Layer ───
export const CLAUDE_TOOLS: Anthropic.Tool[] = [
  {
    name: 'query_vessels',
    description: 'Query AIS vessel positions within a geographic area and time window. Returns vessel name, MMSI, type, position, speed, heading, destination.',
    input_schema: {
      type: 'object' as const,
      properties: {
        lat_min: { type: 'number', description: 'Minimum latitude of bounding box' },
        lat_max: { type: 'number', description: 'Maximum latitude of bounding box' },
        lon_min: { type: 'number', description: 'Minimum longitude of bounding box' },
        lon_max: { type: 'number', description: 'Maximum longitude of bounding box' },
        hours: { type: 'number', description: 'Look-back window in hours (default 24)' },
      },
      required: ['lat_min', 'lat_max', 'lon_min', 'lon_max'],
    },
  },
  {
    name: 'query_aircraft',
    description: 'Query ADS-B aircraft positions within a geographic area. Returns callsign, ICAO24, altitude, velocity, heading, country.',
    input_schema: {
      type: 'object' as const,
      properties: {
        lat_min: { type: 'number' },
        lat_max: { type: 'number' },
        lon_min: { type: 'number' },
        lon_max: { type: 'number' },
        altitude_min: { type: 'number', description: 'Minimum altitude in meters' },
        altitude_max: { type: 'number', description: 'Maximum altitude in meters' },
      },
      required: ['lat_min', 'lat_max', 'lon_min', 'lon_max'],
    },
  },
  {
    name: 'query_conflicts',
    description: 'Query ACLED armed conflict events by region, date range, event type, or actor. Returns event type, location, actors, fatalities, notes.',
    input_schema: {
      type: 'object' as const,
      properties: {
        country: { type: 'string', description: 'Country name filter' },
        lat_min: { type: 'number' },
        lat_max: { type: 'number' },
        lon_min: { type: 'number' },
        lon_max: { type: 'number' },
        days: { type: 'number', description: 'Look-back window in days (default 30)' },
        event_type: { type: 'string', description: 'ACLED event type filter' },
      },
      required: [],
    },
  },
  {
    name: 'query_infrastructure',
    description: 'Query energy infrastructure (power plants, pipelines, refineries) within a bounding box. Returns name, type, capacity, fuel, status, owner.',
    input_schema: {
      type: 'object' as const,
      properties: {
        lat_min: { type: 'number' },
        lat_max: { type: 'number' },
        lon_min: { type: 'number' },
        lon_max: { type: 'number' },
        fuel_type: { type: 'string', description: 'Filter by fuel type (coal, gas, nuclear, wind, solar, hydro)' },
      },
      required: ['lat_min', 'lat_max', 'lon_min', 'lon_max'],
    },
  },
  {
    name: 'query_weather',
    description: 'Query current weather conditions for a specific location. Returns temperature, wind speed/direction, precipitation.',
    input_schema: {
      type: 'object' as const,
      properties: {
        latitude: { type: 'number' },
        longitude: { type: 'number' },
      },
      required: ['latitude', 'longitude'],
    },
  },
  {
    name: 'query_agent_reports',
    description: 'Retrieve recent intelligence reports generated by eYKON Sub-Agents. Returns structured reports with severity, narrative, and entity references.',
    input_schema: {
      type: 'object' as const,
      properties: {
        domain: { type: 'string', description: 'Filter by domain: air_traffic, maritime, conflict_security, energy_infrastructure, satellite_imagery' },
        severity: { type: 'string', description: 'Minimum severity: low, medium, high, critical' },
        hours: { type: 'number', description: 'Look-back window in hours (default 48)' },
      },
      required: [],
    },
  },
];

// ─── System Prompt for Conversational Claude ───
export const CONVERSATIONAL_SYSTEM_PROMPT = `You are the eYKON.ai geopolitical intelligence analyst. You have access to live data on:
- Aircraft positions (ADS-B) — civil and military
- Vessel positions (AIS) — commercial and naval
- Armed conflict events (ACLED) — battles, explosions, protests, violence against civilians
- Energy infrastructure — power plants, pipelines, refineries (Global Energy Monitor)
- Weather conditions (Open-Meteo) — temperature, wind, precipitation
- Intelligence reports from eYKON's autonomous Sub-Agent monitoring system

When a user asks a question:
1. Use your tools to query the relevant data sources. Always query data — never guess.
2. Cross-reference across domains when a query spans multiple topics (e.g., vessel activity + conflict events near the same region).
3. Provide concise, factual, analytical responses. Cite sources and dates.
4. When presenting vessel or aircraft data, include identifying information (MMSI, callsign, type).
5. For conflict data, note event type, actors involved, and fatality counts.
6. Offer follow-up query suggestions based on what you found.

You are NOT speculative. If data is unavailable or inconclusive, say so clearly.
When the user mentions a region (e.g., "Red Sea", "Strait of Hormuz", "Black Sea"), translate it to approximate bounding box coordinates for your tool queries.

Common region bounding boxes:
- Red Sea: lat 12-30, lon 32-44
- Strait of Hormuz: lat 24-28, lon 54-58
- Taiwan Strait: lat 22-26, lon 117-121
- Black Sea: lat 40-47, lon 27-42
- South China Sea: lat 0-23, lon 100-121
- Gulf of Aden: lat 10-16, lon 43-52
- Mediterranean: lat 30-46, lon -6-36
- Baltic Sea: lat 53-66, lon 10-30
- Persian Gulf: lat 24-30, lon 48-56`;
