// ─── PDF renderer for AI ANALYST v2 session transcripts (§9.4) ────
//
// Renders a full session — every turn, with a consolidated provenance
// appendix — as a third-party-presentable PDF. Reuses pdfkit +
// BRAND_TOKENS (no new deps), mirroring the per-query renderer in
// intelligence-analyst/export-pdf.ts but for a multi-turn thread.

import PDFDocument from 'pdfkit';
import { BRAND_TOKENS } from '@/lib/brand/tokens';

export interface SessionPdfTurn {
  role: 'user' | 'assistant';
  content: string;
  toolCalls?: Array<{ name: string; input?: unknown; row_count?: number | null }> | null;
  createdAtIso: string;
}

export interface SessionPdfInput {
  title: string;
  projectName?: string | null;
  modelLabel: string;
  turns: SessionPdfTurn[];
  generatedAtIso: string;
}

const PAGE_MARGIN = 56;
const FONT_BODY = 'Helvetica';
const FONT_BOLD = 'Helvetica-Bold';
const FONT_MONO = 'Courier';
const SIZES = { wordmark: 14, title: 13, h2: 11, body: 10, small: 8, footer: 8 };
const COLORS = {
  ink: BRAND_TOKENS.print.ink,
  inkDim: BRAND_TOKENS.print.inkDim,
  accent: BRAND_TOKENS.print.accent,
  rule: BRAND_TOKENS.print.rule,
};

export async function renderSessionPdf(input: SessionPdfInput): Promise<Buffer> {
  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'LETTER',
      margins: { top: PAGE_MARGIN, bottom: PAGE_MARGIN + 24, left: PAGE_MARGIN, right: PAGE_MARGIN },
      bufferPages: true,
      info: {
        Title: `eYKON Intelligence — ${truncate(input.title, 60)}`,
        Author: BRAND_TOKENS.product.wordmark,
        Subject: 'Geopolitical intelligence session transcript',
        Creator: BRAND_TOKENS.product.name,
      },
    });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    try {
      drawHeader(doc, input);
      for (const turn of input.turns) drawTurn(doc, turn);
      drawProvenanceAppendix(doc, input.turns);
      drawFooters(doc, input.generatedAtIso, input.modelLabel);
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

function drawHeader(doc: PDFKit.PDFDocument, input: SessionPdfInput) {
  doc
    .font(FONT_BOLD).fontSize(SIZES.wordmark).fillColor(COLORS.ink)
    .text(BRAND_TOKENS.product.wordmark, { continued: true })
    .font(FONT_BODY).fontSize(SIZES.small).fillColor(COLORS.inkDim)
    .text(`  ·  ${BRAND_TOKENS.product.tagline}`);
  doc.moveDown(0.6);
  ruleLine(doc, COLORS.accent, 1.2);
  doc.moveDown(0.6);

  doc.font(FONT_BODY).fontSize(SIZES.small).fillColor(COLORS.inkDim).text('Session', { characterSpacing: 1.5 });
  doc.moveDown(0.15).font(FONT_BOLD).fontSize(SIZES.title).fillColor(COLORS.ink).text(input.title, { lineGap: 2 });
  if (input.projectName) {
    doc.moveDown(0.15).font(FONT_BODY).fontSize(SIZES.small).fillColor(COLORS.inkDim)
      .text(`Project: ${input.projectName}`);
  }
  doc.moveDown(0.8);
}

function drawTurn(doc: PDFKit.PDFDocument, turn: SessionPdfTurn) {
  const label = turn.role === 'user' ? 'Analyst asked' : 'eYKON';
  doc
    .font(FONT_BODY).fontSize(SIZES.small).fillColor(turn.role === 'user' ? COLORS.accent : COLORS.inkDim)
    .text(label.toUpperCase(), { characterSpacing: 1.2 });
  doc.moveDown(0.25);
  renderLightMarkdown(doc, turn.content);
  if (turn.role === 'assistant' && turn.toolCalls && turn.toolCalls.length > 0) {
    doc.moveDown(0.2).font(FONT_MONO).fontSize(SIZES.small).fillColor(COLORS.inkDim)
      .text(`tools: ${turn.toolCalls.map((t) => t.name).join(', ')}`);
  }
  doc.moveDown(0.6);
}

function drawProvenanceAppendix(doc: PDFKit.PDFDocument, turns: SessionPdfTurn[]) {
  const calls = turns.flatMap((t) => t.toolCalls ?? []);
  if (calls.length === 0) return;
  doc.moveDown(0.4);
  ruleLine(doc, COLORS.rule, 0.6);
  doc.moveDown(0.4);
  doc.font(FONT_BOLD).fontSize(SIZES.h2).fillColor(COLORS.ink).text('Provenance');
  doc.moveDown(0.3);
  for (const c of calls) {
    const rc = c.row_count != null ? `${c.row_count} rows` : 'n/a';
    doc.font(FONT_MONO).fontSize(SIZES.small).fillColor(COLORS.inkDim)
      .text(`• ${c.name} — ${rc}`);
  }
}

function drawFooters(doc: PDFKit.PDFDocument, generatedAtIso: string, modelLabel: string) {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    const y = doc.page.height - PAGE_MARGIN - 4;
    doc.font(FONT_BODY).fontSize(SIZES.footer).fillColor(COLORS.inkDim);
    doc.text(
      `Generated by ${BRAND_TOKENS.product.name} · ${modelLabel} · ${generatedAtIso}`,
      PAGE_MARGIN, y, { width: doc.page.width - PAGE_MARGIN * 2, align: 'left', lineBreak: false },
    );
    doc.text(
      `${i - range.start + 1} / ${range.count}`,
      PAGE_MARGIN, y, { width: doc.page.width - PAGE_MARGIN * 2, align: 'right', lineBreak: false },
    );
  }
}

// Lightweight markdown: headings (#), bullets (-/*), paragraphs.
function renderLightMarkdown(doc: PDFKit.PDFDocument, text: string) {
  for (const raw of text.split('\n')) {
    const line = raw.replace(/\s+$/, '');
    if (line === '') { doc.moveDown(0.35); continue; }
    if (/^#{1,3}\s+/.test(line)) {
      doc.moveDown(0.2).font(FONT_BOLD).fontSize(SIZES.h2).fillColor(COLORS.ink)
        .text(line.replace(/^#{1,3}\s+/, ''), { lineGap: 1 });
      continue;
    }
    if (/^[-*]\s+/.test(line)) {
      doc.font(FONT_BODY).fontSize(SIZES.body).fillColor(COLORS.ink)
        .text(`•  ${stripInline(line.replace(/^[-*]\s+/, ''))}`, { indent: 8, lineGap: 1 });
      continue;
    }
    doc.font(FONT_BODY).fontSize(SIZES.body).fillColor(COLORS.ink)
      .text(stripInline(line), { lineGap: 1.5 });
  }
}

// Strip **bold**/`code`/*italic* markers — pdfkit has no rich inline runs here.
function stripInline(s: string): string {
  return s.replace(/\*\*(.+?)\*\*/g, '$1').replace(/`(.+?)`/g, '$1').replace(/(?<!\*)\*(?!\*)(.+?)\*/g, '$1');
}

function ruleLine(doc: PDFKit.PDFDocument, color: string, weight: number) {
  const y = doc.y;
  doc.save().moveTo(PAGE_MARGIN, y).lineTo(doc.page.width - PAGE_MARGIN, y)
    .lineWidth(weight).strokeColor(color).stroke().restore();
}

function truncate(s: string, n: number): string {
  return s.length <= n ? s : `${s.slice(0, n - 1)}…`;
}
