-- ═══════════════════════════════════════════════════════════════
-- Migration 033 — Refund requests (PR-OBS-5)
--
-- User-initiated refund flow for the crypto-era trial mechanism.
--
-- Per the trial-mechanism brief §6 (Refund overlay — mechanics):
--   • Window: flat 14 days from purchase date (D1).
--   • Settlement: USDC only (D2).
--   • Eligibility: one refund per user lifetime, independent of auth
--     method (D8).
--   • SLA: 5 business days from request → "sent" status.
--   • Audit trail: every state transition writes to admin_actions
--     (migration 027).
--
-- State machine:
--   pending  → sent  → confirmed (on-chain)
--           ↘ rejected
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS refund_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  purchase_id UUID NOT NULL REFERENCES purchases(id) ON DELETE CASCADE,

  -- Optional free-text "why?" the user typed in the request modal.
  reason TEXT,

  -- pending  → operator hasn't actioned it yet.
  -- sent     → operator has sent USDC; awaiting on-chain confirmation.
  -- confirmed→ tx hash visible on-chain.
  -- rejected → operator rejected (e.g. duplicate, abuse signal).
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','sent','confirmed','rejected')),

  -- Operator identity + free-text note captured at the state transition.
  operator_id UUID REFERENCES auth.users(id),
  operator_note TEXT,

  -- On-chain settlement record. Populated when status='sent', verified
  -- when status='confirmed'.
  refund_tx_hash TEXT,
  refund_amount_usd_cents INTEGER,  -- USDC ≈ USD; informational

  requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sent_at      TIMESTAMPTZ,
  confirmed_at TIMESTAMPTZ,
  rejected_at  TIMESTAMPTZ
);

-- One refund request per purchase (enforces idempotency on user clicks).
-- A user attempting to submit a second request for the same purchase
-- gets a unique-constraint violation rather than a duplicate row.
CREATE UNIQUE INDEX IF NOT EXISTS uq_refund_requests_purchase
  ON refund_requests (purchase_id);

-- One refund per user lifetime (per D8). The check is enforced in
-- application code (api/billing/refund/route.ts) because Postgres
-- can't express "at most one non-rejected refund per user_id" in a
-- single index easily — but a partial unique index covering all
-- non-rejected statuses approximates it and protects against races.
CREATE UNIQUE INDEX IF NOT EXISTS uq_refund_requests_user_lifetime
  ON refund_requests (user_id)
  WHERE status IN ('pending','sent','confirmed');

CREATE INDEX IF NOT EXISTS idx_refund_requests_user
  ON refund_requests (user_id, requested_at DESC);
CREATE INDEX IF NOT EXISTS idx_refund_requests_pending
  ON refund_requests (requested_at DESC)
  WHERE status = 'pending';

-- ─── RLS ─────────────────────────────────────────────────────
ALTER TABLE refund_requests ENABLE ROW LEVEL SECURITY;

-- Users see their own refund requests only. Operators read via the
-- service-role key in /admin/refunds (bypasses RLS).
CREATE POLICY "Users see own refund requests" ON refund_requests
  FOR SELECT USING (auth.uid() = user_id);

-- INSERT is service-role only — the /api/billing/refund route
-- creates rows on the user's behalf after server-side eligibility
-- checks. No anon/auth INSERT policy → RLS blocks direct inserts.

-- UPDATE is service-role only — operator transitions go through
-- /api/admin/refunds/[id]/mark-sent and similar.

-- ─── Updated-at trigger ──────────────────────────────────────
-- No updated_at column on this table; the three timestamp columns
-- (sent_at, confirmed_at, rejected_at) carry transition-specific time
-- so we can reason about each phase independently.

-- ─── admin_actions CHECK constraint extension ────────────────
-- Migration 027 closed the admin_actions table over three referral-
-- specific values. PR-OBS-5 adds refund-flow values so operator
-- mark-sent / mark-rejected actions can be audited there.
--
-- We drop the existing CHECK and re-add with extended sets. If the
-- existing constraint name differs (autogenerated), this will fail
-- loud — adjust the constraint name in the dashboard before re-run.

ALTER TABLE admin_actions
  DROP CONSTRAINT IF EXISTS admin_actions_action_check;
ALTER TABLE admin_actions
  ADD CONSTRAINT admin_actions_action_check CHECK (action IN (
    'force_mark_threshold',
    'force_cancel_accrual',
    'force_create_referral',
    'refund_sent',
    'refund_rejected'
  ));

ALTER TABLE admin_actions
  DROP CONSTRAINT IF EXISTS admin_actions_target_table_check;
ALTER TABLE admin_actions
  ADD CONSTRAINT admin_actions_target_table_check CHECK (target_table IN (
    'referrals',
    'referral_commission_accruals',
    'refund_requests'
  ));
