-- ═══════════════════════════════════════════════════════════════
-- Migration 090 — AI ANALYST v2 workspace: sessions, messages,
--                 projects, insights
--
-- Backs the AI ANALYST v2 build (brief v1.1, 2026-07-22, BACKEND/
-- II - AI ANALYST/v2). Turns the analyst from a stateless side-panel
-- into a session-based workspace:
--
--   analyst_projects  — Pro+ grouping unit ("Red Sea shipping") with
--                       custom instructions injected into the system
--                       prompt for every session in the project.
--   analyst_sessions  — one conversation. Carries persona, model,
--                       origin (workspace | inline | comm), optional
--                       viewport context, optional project.
--   analyst_messages  — one row per turn (user or assistant), with
--                       tool calls + provenance + token usage on
--                       assistant rows. seq gives stable ordering.
--   analyst_insights  — "save as insight" pins an answer to a
--                       project; raw material of the dossier (v1).
--
-- user_queries (mig 021) is NOT touched: it stays read-only for the
-- docked panel's Query History tab and the public share flow until
-- the workspace fully supersedes it.
--
-- Plan gating (decided 2026-07-22, brief §9.6): sessions + history
-- reach Member; projects/export/Deep Analysis are Pro+. Gating is
-- enforced in the API on EFFECTIVE tier (getCurrentTier →
-- tier_overrides); RLS here enforces per-user isolation only.
--
-- Idempotent: CREATE IF NOT EXISTS everywhere; policies guarded with
-- DROP POLICY IF EXISTS, matching the convention from migration 019/021.
-- ═══════════════════════════════════════════════════════════════

-- ─── Projects ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS analyst_projects (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  description   TEXT,
  -- Custom instructions injected into the system prompt for every
  -- session filed under this project (brief §8.4).
  instructions  TEXT,
  color         TEXT,
  pinned        BOOLEAN NOT NULL DEFAULT false,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  archived_at   TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_analyst_projects_user
  ON analyst_projects (user_id, pinned DESC, updated_at DESC)
  WHERE archived_at IS NULL;

-- ─── Sessions ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS analyst_sessions (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  project_id      UUID REFERENCES analyst_projects(id) ON DELETE SET NULL,
  -- Auto-generated by a Haiku call after the first exchange; starts
  -- as 'New session'.
  title           TEXT NOT NULL DEFAULT 'New session',
  persona         TEXT,
  -- Model id actually used for this session. Validated in the API
  -- against the allowed set + the user's tier (Deep Analysis = Pro+).
  model           TEXT,
  -- workspace | inline (docked panel) | comm (in-room analyst)
  origin          TEXT NOT NULL DEFAULT 'workspace'
                  CHECK (origin IN ('workspace', 'inline', 'comm')),
  -- Map context when opened from the globe (brief §6.1 right rail).
  viewport        JSONB,
  pinned          BOOLEAN NOT NULL DEFAULT false,
  message_count   INTEGER NOT NULL DEFAULT 0,
  last_message_at TIMESTAMPTZ,
  share_token     TEXT UNIQUE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  archived_at     TIMESTAMPTZ
);

-- Left-rail list: per-user, pinned first, most recent activity first.
CREATE INDEX IF NOT EXISTS idx_analyst_sessions_user_recent
  ON analyst_sessions (user_id, pinned DESC, last_message_at DESC NULLS LAST)
  WHERE archived_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_analyst_sessions_project
  ON analyst_sessions (project_id)
  WHERE project_id IS NOT NULL;

-- ─── Messages ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS analyst_messages (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id   UUID NOT NULL REFERENCES analyst_sessions(id) ON DELETE CASCADE,
  -- Denormalised so RLS + GDPR cascade never need a join.
  user_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  -- Stable ordering within the session (1, 2, 3, …). The writer
  -- assigns it; unique per session so a race cannot interleave.
  seq          INTEGER NOT NULL,
  role         TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  content      TEXT NOT NULL,
  -- Assistant rows only. tool_calls: [{name, input, row_count}];
  -- provenance mirrors the export block (source, fetched_at,
  -- row_count per tool); token_usage: input/output token counts.
  tool_calls   JSONB,
  provenance   JSONB,
  token_usage  JSONB,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (session_id, seq)
);

CREATE INDEX IF NOT EXISTS idx_analyst_messages_session
  ON analyst_messages (session_id, seq);

-- GDPR "clear my history" and retention sweeps go by user.
CREATE INDEX IF NOT EXISTS idx_analyst_messages_user
  ON analyst_messages (user_id, created_at);

-- ─── Insights (v1 surface; shape landed now so the FK exists) ──

CREATE TABLE IF NOT EXISTS analyst_insights (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  project_id   UUID REFERENCES analyst_projects(id) ON DELETE CASCADE,
  session_id   UUID REFERENCES analyst_sessions(id) ON DELETE SET NULL,
  message_id   UUID REFERENCES analyst_messages(id) ON DELETE SET NULL,
  title        TEXT NOT NULL,
  body         TEXT NOT NULL,
  provenance   JSONB,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_analyst_insights_user
  ON analyst_insights (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_analyst_insights_project
  ON analyst_insights (project_id)
  WHERE project_id IS NOT NULL;

-- ─── Row-Level Security ────────────────────────────────────────
-- Per-user isolation at the database, not just the API. Routes use
-- the service-role client with explicit ownership checks (project
-- convention); RLS is the backstop for any anon/authenticated path.

ALTER TABLE analyst_projects  ENABLE ROW LEVEL SECURITY;
ALTER TABLE analyst_sessions  ENABLE ROW LEVEL SECURITY;
ALTER TABLE analyst_messages  ENABLE ROW LEVEL SECURITY;
ALTER TABLE analyst_insights  ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "self read"   ON analyst_projects;
CREATE POLICY "self read"   ON analyst_projects FOR SELECT USING (user_id = auth.uid());
DROP POLICY IF EXISTS "self write"  ON analyst_projects;
CREATE POLICY "self write"  ON analyst_projects FOR INSERT WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS "self update" ON analyst_projects;
CREATE POLICY "self update" ON analyst_projects FOR UPDATE USING (user_id = auth.uid());
DROP POLICY IF EXISTS "self delete" ON analyst_projects;
CREATE POLICY "self delete" ON analyst_projects FOR DELETE USING (user_id = auth.uid());

DROP POLICY IF EXISTS "self read"   ON analyst_sessions;
CREATE POLICY "self read"   ON analyst_sessions FOR SELECT USING (user_id = auth.uid());
DROP POLICY IF EXISTS "self write"  ON analyst_sessions;
CREATE POLICY "self write"  ON analyst_sessions FOR INSERT WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS "self update" ON analyst_sessions;
CREATE POLICY "self update" ON analyst_sessions FOR UPDATE USING (user_id = auth.uid());
DROP POLICY IF EXISTS "self delete" ON analyst_sessions;
CREATE POLICY "self delete" ON analyst_sessions FOR DELETE USING (user_id = auth.uid());

DROP POLICY IF EXISTS "self read"   ON analyst_messages;
CREATE POLICY "self read"   ON analyst_messages FOR SELECT USING (user_id = auth.uid());
DROP POLICY IF EXISTS "self write"  ON analyst_messages;
CREATE POLICY "self write"  ON analyst_messages FOR INSERT WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS "self delete" ON analyst_messages;
CREATE POLICY "self delete" ON analyst_messages FOR DELETE USING (user_id = auth.uid());

DROP POLICY IF EXISTS "self read"   ON analyst_insights;
CREATE POLICY "self read"   ON analyst_insights FOR SELECT USING (user_id = auth.uid());
DROP POLICY IF EXISTS "self write"  ON analyst_insights;
CREATE POLICY "self write"  ON analyst_insights FOR INSERT WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS "self update" ON analyst_insights;
CREATE POLICY "self update" ON analyst_insights FOR UPDATE USING (user_id = auth.uid());
DROP POLICY IF EXISTS "self delete" ON analyst_insights;
CREATE POLICY "self delete" ON analyst_insights FOR DELETE USING (user_id = auth.uid());
