'use client';
import { useState } from 'react';

export default function BriefingCard() {
  const [loading, setLoading] = useState(false);
  const [briefing, setBriefing] = useState<string | null>(null);
  const today = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });

  const generateBriefing = async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/dashboard/briefing', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ user_id: 'demo-user' }),
      });
      const data = await res.json();
      setBriefing(data.briefing || 'Briefing generation requires Supabase and Anthropic API keys to be configured.');
    } catch {
      setBriefing('Connect your API keys to generate personalised daily briefings.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-eykon-card border border-eykon-border rounded-xl p-4 h-full flex flex-col">
      <div className="flex items-center justify-between mb-3">
        <h2 className="text-sm font-semibold text-white">Daily Briefing</h2>
        <span className="text-[10px] text-eykon-muted">{today}</span>
      </div>

      {briefing ? (
        <div className="flex-1 overflow-y-auto">
          <div className="text-xs text-gray-300 leading-relaxed whitespace-pre-wrap chat-content">
            {briefing}
          </div>
        </div>
      ) : (
        <div className="flex-1 flex flex-col items-center justify-center text-center">
          <div className="text-3xl mb-3">📋</div>
          <p className="text-xs text-eykon-muted mb-3">
            Your personalised intelligence briefing, generated by Claude from your watchlist and recent events.
          </p>
          <button
            onClick={generateBriefing}
            disabled={loading}
            className="px-4 py-1.5 bg-eykon-teal/20 hover:bg-eykon-teal/30 text-eykon-teal text-xs font-medium rounded-lg border border-eykon-teal/30 transition-all disabled:opacity-50"
          >
            {loading ? 'Generating...' : 'Generate Briefing'}
          </button>
        </div>
      )}
    </div>
  );
}
